[2025-04-07T14:31:47.030+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tutorial.sleep scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-07T14:31:47.060+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tutorial.sleep scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-07T14:31:47.065+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-04-07T14:31:47.122+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): sleep> on 2025-04-05 00:00:00+00:00
[2025-04-07T14:31:47.134+0000] {standard_task_runner.py:60} INFO - Started process 456 to run task
[2025-04-07T14:31:47.147+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'sleep', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/tutorial.py', '--cfg-path', '/tmp/tmpt7bk3u3l']
[2025-04-07T14:31:47.161+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask sleep
[2025-04-07T14:31:47.278+0000] {task_command.py:423} INFO - Running <TaskInstance: tutorial.sleep scheduled__2025-04-05T00:00:00+00:00 [running]> on host b1999c8cac41
[2025-04-07T14:31:47.485+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tutorial' AIRFLOW_CTX_TASK_ID='sleep' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-07T14:31:47.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-07T14:31:47.513+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-04-07T14:31:47.545+0000] {subprocess.py:86} INFO - Output:
[2025-04-07T14:31:48.613+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-04-07T14:31:48.627+0000] {process_utils.py:131} INFO - Sending 15 to group 456. PIDs of all processes in the group: [460, 456]
[2025-04-07T14:31:48.628+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 456
[2025-04-07T14:31:48.629+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-07T14:31:48.630+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-07T14:31:48.651+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-07T14:31:48.659+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial, task_id=sleep, execution_date=20250405T000000, start_date=20250407T143147, end_date=20250407T143148
[2025-04-07T14:31:48.698+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task sleep (Task received SIGTERM signal; 456)
[2025-04-07T14:31:48.724+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=460, status='terminated', started='14:31:47') (460) terminated with exit code None
[2025-04-07T14:31:48.726+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=456, status='terminated', exitcode=1, started='14:31:46') (456) terminated with exit code 1
[2025-04-07T14:31:48.727+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-04-07T14:31:48.777+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
